{
 "title": "Services statistic",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average test duration by service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(test_duration_seconds_sum{service=~\"$service\"}[1m])) by (service, testOutcome) / sum by (service, testOutcome) (increase(test_duration_seconds_count{service=~\"$service\"}[1m]))",
       "legendFormat": "{{service}} - {{testOutcome}}"
      }
     ]
    },
    {
     "title": "Test events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (type) (increase(events_total{}[30s]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Income / Expenses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(payments_amount_total{service=~\"$service\"}[1m])) by (service)",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(rate(external_amount_total{service=~\"$service\"}[1m])) by (service, accountName)",
       "legendFormat": "expenses - {{service}}  -  {{accountName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tests info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Tests per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(increase(test_duration_seconds_count{service=~\"$service\", testOutcome!~\"ERROR|FAIL\"}[1m])) by (service)",
       "legendFormat": "{{service}} - success"
      },
      {
       "expr": "sum(increase(test_duration_seconds_count{service=~\"$service\", testOutcome=~\"ERROR|FAIL\"}[1m])) by (service)",
       "legendFormat": "{{service}} - fail"
      }
     ]
    },
    {
     "title": "Success percent (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "increase(test_duration_seconds_count{service=~\"$service\", testOutcome!~\"ERROR|FAIL\"}[1m]) / (increase(test_duration_seconds_count{service=~\"$service\", testOutcome!~\"ERROR|FAIL\"}[1m]) + increase(test_duration_seconds_count{service=~\"$service\", testOutcome!~\"ERROR|FAIL\"}[1m]))",
       "legendFormat": "{{service}} - success"
      }
     ]
    },
    {
     "title": "Test duration quantile 95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "test_duration_seconds{service=~\"$service\", testOutcome!~\"ERROR|FAIL\", quantile=\"0.95\"} ",
       "legendFormat": "{{service}} - success"
      },
      {
       "expr": "test_duration_seconds{service=~\"$service\", testOutcome=~\"ERROR|FAIL\", quantile=\"0.95\"}",
       "legendFormat": "{{service}} - fail"
      }
     ]
    }
   ]
  },
  {
   "title": "Stages info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Success stages number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(stage_duration_ok_seconds_count{service=~\"$service\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Fail stages number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(increase(stage_duration_fail_seconds_count{service=~\"$service\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Success stages duration. Quantile 0.95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "stage_duration_ok_seconds{service=~\"$service\", quantile=\"0.95\"}",
       "legendFormat": "{{stage}}"
      },
      {}
     ]
    },
    {
     "title": "Fail stages duration. Quantile 95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "stage_duration_fail_seconds{service=~\"$service\", quantile=\"0.95\"}",
       "legendFormat": "{{stage}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Http calls info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Http requests rate (rps)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_external_duration_seconds_count{service=~\"$service\"}[30s])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Http requests duration. Quantile 0.95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(http_external_duration_seconds{service=~\"$service\", quantile=\"0.95\"}) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Http response number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(http_external_duration_seconds_count{service=~\"$service\"}[1m])) by (method,code)",
       "legendFormat": "{{method}}/{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executors info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Queued jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      { "expr": "executor_queue_length{}" }
     ]
    },
    {
     "title": "Running jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      { "expr": "executor_run_jobs" }
     ]
    }
   ]
  }
 ]
}