{
 "title": "Services statistic",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "Average test duration by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(test_duration_fail_seconds_sum{}[1m])) by (service) / sum by (service) (increase(test_duration_fail_seconds_count{}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Test events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (increase(events_total{}[30s]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Tests info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(test_duration_ok_seconds_count{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}} - success"
    },
    {
     "expr": "sum(increase(test_duration_fail_seconds_count{service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "{{service}} - fail"
    }
   ]
  },
  {
   "title": "Success percent (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(test_duration_ok_seconds_count{service=~\"$service\"}[1m]) / (increase(test_duration_ok_seconds_count{service=~\"$service\"}[1m]) + increase(test_duration_fail_seconds_count{service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} - success"
    }
   ]
  },
  {
   "title": "Test duration quantile 95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "test_duration_ok_seconds{service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{service}} - success"
    },
    {
     "expr": "test_duration_fail_seconds{service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{service}} - fail"
    }
   ]
  },
  {
   "title": "Stages info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success stages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(stage_duration_ok_seconds_count{service=~\"$service\"}[1m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Fail stages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(stage_duration_fail_seconds_count{service=~\"$service\"}[5m])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Success stages quantile 95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stage_duration_ok_seconds{service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{stage}}"
    },
    {}
   ]
  },
  {
   "title": "Fail stages quantile 95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stage_duration_fail_seconds{service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{stage}}"
    },
    {}
   ]
  },
  {
   "title": "Http calls info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Http requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_external_duration_seconds_count{service=~\"$service\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http requests quantile 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(http_external_duration_seconds{service=~\"$service\", quantile=\"0.95\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http response per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_external_duration_seconds_count{service=~\"$service\"}[1m])) by (method,code)",
     "legendFormat": "{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "Executors info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queued jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    { "expr": "executor_queue_length" }
   ]
  },
  {
   "title": "Running jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    { "expr": "executor_run_jobs" }
   ]
  },
  {
   "title": "Services statistic",
   "panels": [
    {
     "title": "General",
     "type": "row",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
     "collapsed": true,
     "panels": [
      {
       "title": "Payments outcome rate per second",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
       "targets": [
        {
         "expr": "sum(rate(payment_finished_total{service=~\"$service\"}[30s])) by (service, outcome, failReason)",
         "legendFormat": "{{outcome}} - {{failReason}}"
        }
       ]
      },
      {
       "title": "Event during testing per second",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
       "targets": [
        {
         "expr": "sum by (type) (rate(events_total{}[30s]))",
         "legendFormat": "{{type}}"
        }
       ]
      },
      {
       "title": "Income / Expenses percentage",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
       "fieldConfig": { "defaults": { "unit": "percentunit" } },
       "targets": [
        {
         "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
         "legendFormat": "income - {{service}}"
        },
        {
         "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
         "legendFormat": "expenses - {{service}} "
        }
       ]
      },
      {
       "title": "Income / Expenses percentage",
       "type": "stat",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
       "fieldConfig": { "defaults": { "unit": "percentunit" } },
       "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
       "targets": [
        {
         "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
         "legendFormat": "income - {{service}}"
        },
        {
         "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
         "legendFormat": "expenses - {{service}} "
        }
       ]
      },
      {
       "title": "Income / Expenses amount",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
       "fieldConfig": { "defaults": { "unit": "short" } },
       "targets": [
        {
         "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service)",
         "legendFormat": "income - {{service}}"
        },
        {
         "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service, accountName) ",
         "legendFormat": "expenses - {{service}} - {{accountName}}"
        }
       ]
      },
      {
       "title": "Income / Expenses amount",
       "type": "stat",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
       "fieldConfig": { "defaults": { "unit": "short" } },
       "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
       "targets": [
        {
         "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service)",
         "legendFormat": "income - {{service}}"
        },
        {
         "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service, accountName) ",
         "legendFormat": "expenses - {{service}} - {{accountName}}"
        }
       ]
      }
     ]
    },
    {
     "title": "Tests info",
     "type": "row",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
     "collapsed": true,
     "targets": [
      {}
     ],
     "panels": [
      {
       "title": "Tests run",
       "type": "stat",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
       "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
       "targets": [
        {
         "expr": "sum(increase(test_duration_seconds_count{service=~\"$service\"}[$__range])) by (service, testOutcome)",
         "legendFormat": "{{service}} - {{testOutcome}}"
        }
       ]
      },
      {
       "title": "Success percent (per minute)",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
       "fieldConfig": { "defaults": { "unit": "percentunit" } },
       "targets": [
        {
         "expr": "(sum by(service)(increase(test_duration_seconds_count{service=~\"$service\", testOutcome=~\"SUCCESS\"}[1m]))) / (sum by(service) (increase(test_duration_seconds_count{service=~\"$service\", testOutcome=~\".*\"}[1m])))",
         "legendFormat": "{{service}} - success"
        }
       ]
      },
      {
       "title": "Test duration. Quantile 95",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
       "fieldConfig": { "defaults": { "unit": "s" } },
       "targets": [
        {
         "expr": "test_duration_seconds{service=~\"$service\", quantile=\"0.95\"} ",
         "legendFormat": "{{service}} - {{testOutcome}}"
        }
       ]
      },
      {
       "title": "Average test duration by service",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
       "fieldConfig": { "defaults": { "unit": "s" } },
       "targets": [
        {
         "expr": "sum(rate(test_duration_seconds_sum{service=~\"$service\"}[1m])) by (service, testOutcome) / sum by (service, testOutcome) (rate(test_duration_seconds_count{service=~\"$service\"}[1m]))",
         "legendFormat": "{{service}} - {{testOutcome}}"
        }
       ]
      }
     ]
    },
    {
     "title": "Stages info",
     "type": "row",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
     "collapsed": true,
     "targets": [
      {}
     ],
     "panels": [
      {
       "title": "Success stages number per minute",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
       "targets": [
        {
         "expr": "sum(increase(stage_duration_ok_seconds_count{service=~\"$service\"}[1m])) by (stage)",
         "legendFormat": "{{stage}}"
        }
       ]
      },
      {
       "title": "Fail stages number per minute",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
       "targets": [
        {
         "expr": "sum(increase(stage_duration_fail_seconds_count{service=~\"$service\"}[1m])) by (stage)",
         "legendFormat": "{{stage}}"
        }
       ]
      },
      {
       "title": "Success stages duration. Quantile 0.95",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
       "fieldConfig": { "defaults": { "unit": "s" } },
       "targets": [
        {
         "expr": "stage_duration_ok_seconds{service=~\"$service\", quantile=\"0.95\"}",
         "legendFormat": "{{stage}}"
        },
        {}
       ]
      },
      {
       "title": "Fail stages duration. Quantile 95",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
       "fieldConfig": { "defaults": { "unit": "s" } },
       "targets": [
        {
         "expr": "stage_duration_fail_seconds{service=~\"$service\", quantile=\"0.95\"}",
         "legendFormat": "{{stage}}"
        },
        {}
       ]
      },
      {
       "title": "Success stages duration. Average",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
       "fieldConfig": { "defaults": { "unit": "s" } },
       "targets": [
        {
         "expr": "rate(stage_duration_ok_seconds_sum{service=~\"$service\"}[1m]) / rate(stage_duration_ok_seconds_count{service=~\"$service\"}[1m])",
         "legendFormat": "{{stage}}"
        },
        {}
       ]
      }
     ]
    },
    {
     "title": "Http calls info",
     "type": "row",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
     "collapsed": true,
     "targets": [
      {}
     ],
     "panels": [
      {
       "title": "(Test system -> Online shop) http requests processed rate (rps)",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
       "fieldConfig": { "defaults": { "unit": "short" } },
       "targets": [
        {
         "expr": "sum(rate(http_external_duration_seconds_count{service=~\"$service\"}[30s])) by (method)",
         "legendFormat": "{{method}}"
        }
       ]
      },
      {
       "title": "(Test system -> Online shop) http requests duration. Average",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
       "fieldConfig": { "defaults": { "unit": "s" } },
       "targets": [
        {
         "expr": "rate(http_external_duration_seconds_sum{service=~\"$service\"}[1m]) / rate(http_external_duration_seconds_count{service=~\"$service\"}[1m])",
         "legendFormat": "{{method}} - {{result}}"
        }
       ]
      },
      {
       "title": "(Online shop -> External system)  http requests duration. Quantile 0.95",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
       "fieldConfig": { "defaults": { "unit": "s" } },
       "targets": [
        {
         "expr": "sum(external_sys_duration_seconds{service=~\"$service\", quantile=\"0.95\"}) by (accountName, outcome)",
         "legendFormat": "{{accountName}} - {{outcome}}"
        }
       ]
      },
      {
       "title": "External sys processing duration. Average",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
       "fieldConfig": { "defaults": { "unit": "s" } },
       "targets": [
        {
         "expr": "rate(external_sys_duration_seconds_sum{service=~\"$service\"}[1m]) / rate(external_sys_duration_seconds_count{service=~\"$service\"}[1m])",
         "legendFormat": "{{accountName}} - {{outcome}}"
        }
       ]
      },
      {
       "title": "External system incoming http requests rate",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
       "fieldConfig": { "defaults": { "unit": "none" } },
       "targets": [
        {
         "expr": "rate(external_sys_duration_seconds_count{service=~\"$service\"}[30s])",
         "legendFormat": "{{accountName}} - {{outcome}}"
        }
       ]
      }
     ]
    },
    {
     "title": "Executors info",
     "type": "row",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
     "collapsed": true,
     "targets": [
      {}
     ],
     "panels": [
      {
       "title": "Queued jobs",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
       "targets": [
        {
         "expr": "max by (name) (executor_queued_tasks{service=~\"$service\"})",
         "legendFormat": "{{name}}"
        }
       ]
      },
      {
       "title": "Running jobs",
       "type": "timeseries",
       "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
       "targets": [
        {
         "expr": "sum by (name) (rate(executor_completed_tasks_total{}[1m]))",
         "legendFormat": "{{name}}"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}