{
 "title": "Services statistic",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Payments outcome rate per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(payment_finished_total{service=~\"$service\"}[30s])) by (service, outcome, failReason)",
       "legendFormat": "{{outcome}} - {{failReason}}"
      }
     ]
    },
    {
     "title": "Event during testing per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum by (type) (rate(events_total{}[30s]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Income / Expenses percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service))",
       "legendFormat": "expenses - {{service}} "
      }
     ]
    },
    {
     "title": "Income / Expenses percentage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service) / (sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service) + sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service))",
       "legendFormat": "expenses - {{service}} "
      }
     ]
    },
    {
     "title": "Income / Expenses amount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[1m])) by (service)",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[1m])) by (service, accountName) ",
       "legendFormat": "expenses - {{service}} - {{accountName}}"
      }
     ]
    },
    {
     "title": "Income / Expenses amount",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(payments_amount_total{service=~\"$service\"}[$__range])) by (service)",
       "legendFormat": "income - {{service}}"
      },
      {
       "expr": "sum(increase(external_amount_total{service=~\"$service\"}[$__range])) by (service, accountName) ",
       "legendFormat": "expenses - {{service}} - {{accountName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tests info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Tests run",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(test_duration_seconds_count{service=~\"$service\"}[$__range])) by (service, testOutcome)",
       "legendFormat": "{{service}} - {{testOutcome}}"
      }
     ]
    },
    {
     "title": "Success percent (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by(service)(increase(test_duration_seconds_count{service=~\"$service\", testOutcome=~\"SUCCESS\"}[1m]))) / (sum by(service) (increase(test_duration_seconds_count{service=~\"$service\", testOutcome=~\".*\"}[1m])))",
       "legendFormat": "{{service}} - success"
      }
     ]
    },
    {
     "title": "Test duration. Quantile 95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "test_duration_seconds{service=~\"$service\", quantile=\"0.95\"} ",
       "legendFormat": "{{service}} - {{testOutcome}}"
      }
     ]
    },
    {
     "title": "Average test duration by service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(test_duration_seconds_sum{service=~\"$service\"}[1m])) by (service, testOutcome) / sum by (service, testOutcome) (rate(test_duration_seconds_count{service=~\"$service\"}[1m]))",
       "legendFormat": "{{service}} - {{testOutcome}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stages info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Success stages number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(stage_duration_ok_seconds_count{service=~\"$service\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Fail stages number per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(stage_duration_fail_seconds_count{service=~\"$service\"}[1m])) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Success stages duration. Quantile 0.95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "stage_duration_ok_seconds{service=~\"$service\", quantile=\"0.95\"}",
       "legendFormat": "{{stage}}"
      },
      {}
     ]
    },
    {
     "title": "Fail stages duration. Quantile 95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "stage_duration_fail_seconds{service=~\"$service\", quantile=\"0.95\"}",
       "legendFormat": "{{stage}}"
      },
      {}
     ]
    },
    {
     "title": "Success stages duration. Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stage_duration_ok_seconds_sum{service=~\"$service\"}[1m]) / rate(stage_duration_ok_seconds_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{stage}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Http calls info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "(Test system -> Online shop) http requests processed rate (rps)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_external_duration_seconds_count{service=~\"$service\"}[30s])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "(Test system -> Online shop) http requests duration. Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_external_duration_seconds_sum{service=~\"$service\"}[1m]) / rate(http_external_duration_seconds_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{method}} - {{result}}"
      }
     ]
    },
    {
     "title": "(Online shop -> External system)  http requests duration. Quantile 0.95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(external_sys_duration_seconds{service=~\"$service\", quantile=\"0.95\"}) by (accountName, outcome)",
       "legendFormat": "{{accountName}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "External sys processing duration. Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(external_sys_duration_seconds_sum{service=~\"$service\"}[1m]) / rate(external_sys_duration_seconds_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{accountName}} - {{outcome}}"
      }
     ]
    },
    {
     "title": "External system incoming http requests rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(external_sys_duration_seconds_count{service=~\"$service\"}[30s])",
       "legendFormat": "{{accountName}} - {{outcome}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executors info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Queued jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "max by (name) (executor_queued_tasks{service=~\"$service\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Running jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum by (name) (rate(executor_completed_tasks_total{}[1m]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage (XMX%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum ((sum by (job, area) (jvm_memory_used_bytes{area=\"heap\"}) / sum by (job, area) (jvm_memory_max_bytes{area=\"heap\"})) * 100) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "JVM threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (jvm_threads_live_threads{})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (process_files_open_files{})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{}[5m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}